export default function Head() {
    return (
        <>
            <meta content="width=device-width, initial-scale=1" name="viewport" />
            <meta name="description" content="A coding challenge solution (Generated by create next app)" />

            <title>Registration form (with Next)</title>
            <link rel="icon" href="/favicon.ico" />
        </>
    );
}
